// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestCase1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testCase1() {
    driver.get("https://nova-park.ru//");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.linkText("НАПРАВЛЕНИЯ")).click();
    driver.findElement(By.linkText("ПОСТУПЛЕНИЕ")).click();
    driver.findElement(By.linkText("ПЕДАГОГАМ")).click();
    driver.findElement(By.linkText("ДЕТЯМ")).click();
    driver.findElement(By.linkText("МУЗЕЙ")).click();
    driver.findElement(By.linkText("VR-ТУР")).click();
    driver.findElement(By.linkText("РАСПИСАНИЕ")).click();
  }
}
